### ISSUE TITLE
Request readthedocs twitchpy

### ISSUE THREAD

**Issue by MrSniFo** [elken/twitchPy#2]
Hi @elken,

I hope you're doing well! I wanted to inquire if you’re still using ReadTheDocs for your project. If not, would it be possible for you to transfer the project maintainership to me? I’m planning to use the name "Twitchpy" as I’ll soon be getting the PyPI package "twitch.py."

Thanks so much for your understanding, and I look forward to your response!

**Comment by MrSniFo** [comment]
https://twitchpy.readthedocs.io/en/latest/

**Comment by MrSniFo** [comment]
https://github.com/sleibrock/twitch.py/issues/1

**Comment by elken** [comment]
I don't own the name, do what you want

**Comment by MrSniFo** [comment]
Hi @elken,

Thanks for your response!

I understand that you may not own the name, but it seems the ReadTheDocs project is still linked to your GitHub account. You can find it here: [Twitchpy ReadTheDocs](https://readthedocs.org/projects/twitchpy/), where your name appears as the maintainer.

Would you be able to transfer the maintainership to me? That way, I can take over and update the documentation accordingly.

Thanks again for your help, and I appreciate your understanding!

Best regards,  
@MrSniFo
![xxxx](https://github.com/user-attachments/assets/87f79f79-71f7-4ba1-b29e-d7f9b229a167)
